# Generated by Django 5.0.1 on 2024-01-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_information', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('hymn_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('hymn_order', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('date_received', models.DateField()),
                ('style', models.CharField(choices=[('marcha', 'Marcha'), ('valsa', 'Valsa'), ('mazurca', 'Mazurca')], max_length=10)),
                ('repetitions', models.CharField(blank=True, max_length=255, null=True)),
                ('footnote', models.TextField(blank=True, null=True)),
                ('offered_to_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_hymns', to='hymn_catalog.person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymn_catalog.person')),
            ],
        ),
        migrations.CreateModel(
            name='Strophe',
            fields=[
                ('strophe_id', models.AutoField(primary_key=True, serialize=False)),
                ('strophe_order', models.IntegerField()),
                ('text', models.TextField()),
                ('hymn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hymn_catalog.hymn')),
            ],
        ),
    ]
